---
homebrew_installed_packages: []

homebrew_taps: []

homebrew_cask_apps:
  - calibre
  - steam
  - xld

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  #

apt_packages: []
  # - name: linux-headers
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
