---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Include default var files
      include_vars: default.config.yml

    - name: Include home var files
      include_vars: home.config.yml
      when: ansible_domain == "home"

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - import_tasks: tasks/ansible-setup.yml

    - import_tasks: tasks/homebrew.yml
      when: ansible_os_family == "Darwin"

    - name: Check if additional packages should be installed
      set_fact: 
        additional_packages = true
      when: composer_packages|len>0 or gem_packages|len>0 or  npm_packages|len>0 or pip_packages|len>0 or apt_packages|len>0 or rpm_packages|len>0

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
      when: additional_packages